name: Build

on: push

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
          if-no-files-found: error

  build_linux_wheels:
    name: Build Linux wheels on ${{ matrix.arch }}
    needs: build_sdist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [
          x86_64,
          i686,
          aarch64,
          ppc64le,
          s390x
        ]
      fail-fast: false
    container: quay.io/pypa/manylinux2014_${{ matrix.arch }}
    steps:
      - name: Set Rust target
        run: |
          case ${{ matrix.arch }} in
            ppc64le) ARCH=powerpc64le ;;
            *) ARCH=${{ matrix.arch }} ;;
          esac
          echo CARGO_BUILD_TARGET=$ARCH-unknown-gnu >>"$GITHUB_ENV"

      - name: Set up QEMU
        if: matrix.arch != 'x86_64' && matrix.arch != 'i686'
        uses: docker/setup-qemu-action@v2

      - name: Install Rust
        run: >
          curl -sSf https://sh.rustup.rs |
          sh -s --
            -y
            --verbose
            --profile=minimal
            --default-host=$CARGO_BUILD_TARGETS

      # - name: Build wheel
      #   run:

      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: ./wheelhouse/*.whl
